export const ADD_TODO = "ADD_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const UPDATE_TODO = "UPDATE_TODO";
export const TASK_COMPLETED="TASK_COMPLETED";
export const DELETE_COMPLETED_TASK="DELETE_COMPLETED_TASK";
export const SHOW_COMPLETED_TASK="SHOW_COMPLETED_TASK";
export const SHOW_UNCOMPLETED_TASK="SHOW_UNCOMPLETED_TASK";
export const SHOW_ALL="SHOW_ALL"